### ISSUE TITLE
🐛 When asking Who is Free today? We get yesterday

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.SophieBot#435]
Cc: @pierssinclairssw @adamcogan 

Hi @jimmidier 

### Describe the Bug

When I asked Who is free today? at 9:49am on the 24th January (Brisbane time) I receive results showing 23rd January.  However when I asked the same question at 10:30 I received the correct results.
### To Reproduce
1.  Open SophieBot team chat
2. Ask Who is free today?

### Expected Behavior

I expect the date to reflect today date at all times

### Tasks
1. Please investigate and fix

### Environment
 - Windows 10
 - Teams
 

### Screenshots

![2022-01-24_10-42-40](https://user-images.githubusercontent.com/58454534/150705324-03db1a36-08a9-456b-b7cf-2a22f32b104d.png)
Figure: Sunday 23rd January shown when it should be Monday 24th

Thanks!

**Comment by jimmidier** [comment]
This issue was caused by a time zone issue. Solved by letting the bot to fetch the client date for “today”.

![image](https://user-images.githubusercontent.com/16027480/150905350-746331fd-e02c-40b2-9ed8-47d06ed25e5d.png)
**Figure: Simulating 9:29 am 24th Sydney for client + 22:29 pm 23th UTC for server and got the correct response (I didn’t take a screenshot of my local time but it was set to be the Sydney time so ignore the Teams version)**
